spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: Quan1314521
    url: jdbc:mysql://localhost:3306/cruddemo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      ## 最小空闲连接数量
      minimum-idle: 5
      ## 空闲连接存活最大时间，默认600000（10分钟
      idle-timeout: 600000
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 10
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 连接池名称
      pool-name: HikariCP
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 18000000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    ## thymeleaf 关闭缓存
    cache: false
    servlet:
      content-type: text/html

  #redis
  redis:
    #redis数据库索引（默认为0）
    database: 0
    #redis服务器地址
    host: 49.232.137.183
    #redis端口号
    port: 6379
    #redis密码
    password: kaikaikaikai
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）默认为8
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）默认为-1
        max-wait: -1
        max-idle: 8
        min-idle: 0
  ##rabbitmq
  rabbitmq:
    host: 192.168.0.102
    username: guest
    password: guest
    virtual-host: /

server:
  servlet:
    ## 配置项目访问路径
    context-path: /crud
  ## 端口号
  port: 80



#mybatis
mybatis:
  type-aliases-package: com.quan.crud.entity
  mapper-locations: classpath:com/quan/crud/entity/**/*.xml


